[build]
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[dev]
  command = "npm run start"
  port = 3000
  targetPort = 3000
  framework = "next"
